export { default as AboutCompany } from './AboutCompany'
export { default as Description } from './Description'
export { default as HowItWorks } from './HowItWorks'
export { default as Advantages } from './Advantages'
export { default as ChooseBots } from './ChooseBots'
export { default as ContactUs } from './ContactUs'