interface Resources {
  "translation": {
    "description": "DESCRIPTION",
    "aboutCompany": "ABOUT COMPANY",
    "advantages": "ADVANTAGES",
    "howItWorks": "HOW IT WORKS",
    "botUsage": "BOT USAGE",
    "buy": "PURCHASE",
    "back": "BACK",
    "month": "month",
    "week": "week",
    "year": "year",
    "premium": "premium",
    "standard": "standard",
    "bannerPart1": "Invest Smarter",
    "bannerPart2": "in Crypto with Our",
    "bannerPart3": "AI Bot",
    "rights": "All rights reserved",
    "errorBots": "Unfortunately bots are not available",
    "errorBot": "Bot was not found",
    "tokenError": "Error status",
    "botNotAvailableBtn": "not available",
    "botAvailableBtn": "Сhoose plan",
    "contactFormName": "Name",
    "contactFormEmail": "Email",
    "contactFormMessage": "Message",
    "RequiredFieldsMessage": "Please fill all required fields",
    "SendBtn": "Send",
    "contactFormSuccessfullySent": "The message sent successfully",
    "choosePlanPromo": "Promocode",
    "choosePlanPromoInput": "Insert your promocode",
    "choosePlanPromoCheck": "check",
    "choosePlanPromoDelete": "delete",
    "choosePlanPromoNotValid": "The promocode is not valid",
    "choosePlanPromoMonth": "month",
    "choosePlanPromoWeek": "week",
    "choosePlanPromoYear": "year",
    "choosePlanPromoProceed": "Proceed",
    "confirmTransactionTransaction": "Transaction",
    "confirmTransactionToken": "Token",
    "confirmTransactionEmail": "Email",
    "errorMessage": "Something went wrong",
    "errorMessage401": "You aren't authorized to see this",
    "errorMessage503": "Looks like our API is down",
    "errorStatus": "status",
    "homeDescription": "Description",
    "homeDescriptionPart1": "Our project offers a suite of",
    "homeDescriptionPart2": " nine advanced Telegram bots",
    "homeDescriptionPart3": "designed to enhance your trading strategy with real-time alerts and analytics. Each bot specializes in a unique aspect of trading, providing tailored insights and recommendations to optimize your",
    "homeDescriptionPart4": "trading decisions",
    "homeAboutCompany": "About Company",
    "homeAboutCompanyPart1": "At",
    "homeAboutCompanyPart2": "FinTech Pilot",
    "homeAboutCompanyPart3": ", we are dedicated to empowering traders with advanced, AI-driven trading assistant bots that revolutionize your interaction with financial markets. Our team of finance professionals, data scientists, and software engineers have united their skills to craft a suite of bots designed to meet all your trading needs. We prioritize accuracy and timeliness, ensuring our clients maintain a competitive edge in the fast-paced trading world. Join us to experience the pinnacle of trading intelligence and make informed decisions confidently.",
    "homeAdvantages": "Advantages",
    "homeAdvantagesDecisionPart1": "Enhanced Decision-Making:",
    "homeAdvantagesDecisionPart2": "Our bots provide you with real-time data analysis empowering you to make more informed and strategic decisions in your trading endeavors.",
    "homeAdvantagesTimePart1": "Time Efficiency:",
    "homeAdvantagesTimePart2": "Automate your trading processes to save time and focus on strategizing rather than manual monitoring.",
    "homeAdvantagesAccessibilityPart1": "Accessibility:",
    "homeAdvantagesAccessibilityPart2": "Easy-to-use and accessible from anywhere, our bots ensure you never miss a valuable trading opportunity.",
    "homeHowItWorks": "How it works?",
    "homeHowItWorksSelectBot": "Select a Bot",
    "homeHowItWorksSelectBotText": "Choose the trading assistant bot that best fits your needs.",
    "homeHowItWorksSubscriptionDuration": "Subscription Duration",
    "homeHowItWorksSubscriptionDurationText": "Choose the duration of your subscription - week, month, or year",
    "homeHowItWorksSubscriptionType": "Subscription Type",
    "homeHowItWorksSubscriptionTypeText": "Decide between Standard and Premium subscription types.",
    "homeHowItWorksPricing": "View Pricing",
    "homeHowItWorksPricingText": " Review the total price for your selected bot, subscription duration, and type.",
    "homeHowItWorksConfirmation": "Plan Confirmation",
    "homeHowItWorksConfirmationText": "After you have chosen the duration and type of subscription, confirm your plan and proceed to your online wallet.",
    "homeHowItWorksCrypto": "Crypto Payment",
    "homeHowItWorksCryptoText": "Send the specified amount to the company's cryptocurrency wallet. You will need to save the transaction number to enter it into the request form to receive the key.",
    "homeHowItWorksTransaction": "Transaction Confirmation",
    "homeHowItWorksTransactionText": " Wait for 5-10 minutes to ensure the transaction is confirmed.",
    "homeHowItWorksBuy": "Buy Key",
    "homeHowItWorksBuyText": "Navigate to the Purchase section on the website, enter the transaction number/address, token of the selected plan, email, and click the 'Get Key' button",
    "homeHowItWorksActive": "Activate Bot",
    "homeHowItWorksActiveText": "Enter the received key in the bot after the /start command to activate your subscription. Learn more <1>here</1>.",
    "chooseBot": "Choose your Bot",
    "contactUsContact": "Contact with us",
    "contactUsOr": "OR",
    "notification": "Notification",
    "choosePlanNotificationReady": "Your plan is ready",
    "choosePlanNotificationError": "Error status",
    "contactFormNotificationSuccessful": "The message sent successfully",
    "contactFormNotificationError": "Something went wrong",
    "errorBoundary1": "status",
    "errorBoundary2": "Error happened",
    "congratulationsFreeBots": "Great, you got {{count}} free bots",
    "congratulationsDiscount": "Great, you got a discount {{discount}}%",
    "botNotAvailable": "This bot is not available yet",
    "confirmationTransactionTitle": "Just one step to your bot",
    "confirmationTransactionPayment": "After selecting a plan, you need to pay the cost of the bot to the company's cryptocurrency wallet:",
    "confirmationTransactionSaveTransaction": "Save the transaction number after making the payment. Please enter it into the appropriate form and provide your email address, to which we will send the key for activating the bot.",
    "confirmationTransactionTokenPrecaution": "Please note that the token for the selected plan is active for 15 minutes. If the token expires or you do not have it, you simply need to reselect the plan.",
    "confirmationTransactionSafety": "We strive to maximize the convenience of our customers. In case the token expires, your payment remains valid, and the transaction is considered successful only after you provide us with the token and the transaction number. This means you can make the payment on one day and confirm the transaction on another: as soon as you confirm the transaction, we will immediately send you the key for activating the bot. So if the token expires, don't worry: just select the same plan for which the payment was made.",
    "confirmationTransactionToken": "Token",
    "confirmationTransactionTransaction": "Transaction ID",
    "confirmationTransactionGetKey": "Get Key",
    "walletAddress": "Wallet Address",
    "network": "Network",
    "confirmationTransactionDone": "Great! We have sent the key to your email.",
    "confirmationTransactionError": "Unfortunately, something went wrong",
    "token": "Token",
    "transactionIsNotFound": "Transaction is not found",
    "invalidToken": "Invalid token",
    "wrongPurchaseAmount": "Wrong purchase amount",
    "transactionWasAlreadyUsed": "Transaction is already used",
    "botUsageTitlePart1": "How",
    "botUsageTitlePart2": "to start",
    "botUsageTitlePart3": "using",
    "botUsageTitlePart4": "the bot",
    "botUsagestepFirtTitle": "Getting Started",
    "botUsagestepSecondTitle": "Entering the Activation Key",
    "botUsagestepThirdTitle": "Selecting the Interface Language",
    "botUsagestepForthTitle": "Ready to Use",
    "botUsagestepFirtsText": "To get started, click the Start button after following the link to the desired bot. This will allow you to begin the bot activation process.",
    "botUsagestepSecondText": "Enter the bot's activation key in the appropriate field. This key is necessary to verify your account and activate all bot features.",
    "botUsagestepThirdText": "Select your preferred interface language from the provided list. This will allow you to use the bot in a language that is convenient for you.",
    "botUsagestepForthText": "All set! You can now use all the services of this bot. Enjoy the convenience and functionality of our service.",
    "confirmationTransactionTokenNotGenerated": "It seems you haven't selected a plan, or you already have a token?",
    "link": "Link"
  }
}

export default Resources;
